name: Build and Deploy

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore GameOverlay.sln
    
    - name: Set build version
      shell: pwsh
      run: |
        $version = "${{ github.ref_name }}" -replace '^v', ''
        echo "VERSION=$version" >> $env:GITHUB_ENV
    
    - name: Build solution in Release mode
      run: dotnet build GameOverlay.sln --configuration Release -p:Version=$env:VERSION --no-restore
    
    - name: Create release artifacts
      run: |
        # Create release directory
        New-Item -ItemType Directory -Path "release" -Force
        
        $sourcePath = "GameHelper\bin\Release\net8.0"
        if (Test-Path $sourcePath) {
          Copy-Item -Path "$sourcePath\*" -Destination "release\" -Recurse -Force
        }
        
        Compress-Archive -Path "release\*" -DestinationPath "GameHelper-${{ github.ref_name }}.zip"
      shell: pwsh
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          GameHelper-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
        generate_release_notes: true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts-${{ github.ref_name }}
        path: release/
        retention-days: 30
